# Generated by Django 4.1.7 on 2023-03-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0002_alter_submenu_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submenu",
            name="url_name",
        ),
        migrations.AddField(
            model_name="submenu",
            name="slug",
            field=models.SlugField(default="default"),
            preserve_default=False,
        ),
    ]
