# Generated by Django 4.1.7 on 2023-03-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menuapp", "0003_remove_submenu_url_name_submenu_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submenu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If this field is blank, so this is the first layer of submenus",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menuapp.submenu",
            ),
        ),
        migrations.AlterField(
            model_name="submenu",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
